name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git fetch --prune --unshallow
      - run: npm ci
      - run: sudo apt-get install xvfb
      - run: npm run build
      - run: xvfb-run --auto-servernum npm run ci-test
        env:   
          CI: true
          DISPLAY: 99.0
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: build & analyze with sonar
        uses: sonarsource/sonarcloud-github-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
